// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBz2NgU-BYvdAZj6ZVTY9FQR1VPzAL9DrY',
    appId: '1:146569334520:web:578d962277eddaddc8350d',
    messagingSenderId: '146569334520',
    projectId: 'quiz-4a9d0',
    authDomain: 'quiz-4a9d0.firebaseapp.com',
    storageBucket: 'quiz-4a9d0.appspot.com',
    measurementId: 'G-QLNLVGXS1C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyChecwg1a6GftEpZUT5d1VazBLuWc8b9K0',
    appId: '1:146569334520:android:1c4c6d15cfb6e99cc8350d',
    messagingSenderId: '146569334520',
    projectId: 'quiz-4a9d0',
    storageBucket: 'quiz-4a9d0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZSspxKrxFD5r9j0EteA1QkvWb6JOx30g',
    appId: '1:146569334520:ios:c597ad6e6267fbefc8350d',
    messagingSenderId: '146569334520',
    projectId: 'quiz-4a9d0',
    storageBucket: 'quiz-4a9d0.appspot.com',
    iosClientId: '146569334520-tbse1t481q0jv6uuqe8pk7t84uqf70up.apps.googleusercontent.com',
    iosBundleId: 'com.appeXper1ence.quesapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDZSspxKrxFD5r9j0EteA1QkvWb6JOx30g',
    appId: '1:146569334520:ios:c597ad6e6267fbefc8350d',
    messagingSenderId: '146569334520',
    projectId: 'quiz-4a9d0',
    storageBucket: 'quiz-4a9d0.appspot.com',
    iosClientId: '146569334520-tbse1t481q0jv6uuqe8pk7t84uqf70up.apps.googleusercontent.com',
    iosBundleId: 'com.appeXper1ence.quesapp',
  );
}
